Repository rzellem/EXOTIC, pull requests merged in 2025-01, with the labels that each got.

#1353 Issue #1352: Fix for EXOTIC LDTk Numba incompatibilities under Python 3.11+
  exotic/version.py
  requirements.txt
Labels: bug, release candidate

#1354 Release EXOTIC 4.3.0: Comparison star identification, image frame management and dependency error fixes
  exotic/api/colab.py
  exotic/exotic.py
  exotic/plots.py
  exotic/version.py
  requirements.txt
Labels: bug, enhancement, release candidate

#1357 Release EXOTIC 4.3.0: Comparison star identification, image frame management and dependency error fixes
  requirements.txt
Labels: bug, enhancement, release candidate

#1359 Issue 1358: Resolve application error when calibration files are nonexistent
  exotic/exotic.py
Labels: bug, release candidate, High-priority

#1360 Release EXOTIC 4.3.1 Hotfix: Fix error when calibration files are nonexistent
  exotic/exotic.py
Labels: bug, release candidate, High-priority

#1363 Normalize develop and main branches
  exotic/version.py
Labels: tracking_only
